import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Plus_Jakarta_Sans, Dancing_Script, Great_Vibes, Monoton, Kaushan_Script, Qwigley } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout";
import Layout from "../components/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: 'swap'
});

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-alt-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: 'swap'
});

const dancingScript = Dancing_Script({
  variable: "--font-cursive",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: 'swap'
});

const greatVibes = Great_Vibes({
  variable: "--font-script",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap'
});

const monoton = Monoton({
  variable: "--font-monoton",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap'
});

const kaushanScript = Kaushan_Script({
  variable: "--font-kaushan",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap'
});

const qwigley = Qwigley({
  variable: "--font-qwigley",
  subsets: ["latin"],
  weight: ["400"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark" data-theme="dark" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Monoton&family=Kaushan+Script&family=Qwigley&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${plusJakarta.variable} ${dancingScript.variable} ${greatVibes.variable} ${monoton.variable} ${kaushanScript.variable} ${qwigley.variable} antialiased bg-neutral-950 text-neutral-100`}>
        <ClientLayout>
          <Layout>{children}</Layout>
        </ClientLayout>
      </body>
    </html>
  );
}
